import { EventItem, AttendanceRecord, StaffUser } from '../types';

export const INITIAL_STAFF_USERS: StaffUser[] = [
  {
    id: 'staff-elena',
    name: 'Dra. Elena Ramos',
    email: 'elena.ramos@bienestar.edu.co',
    role: 'lider_bienestar',
    role_display: 'Líder de Bienestar — Administrador General',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    gender: 'female',
    category_scope: 'all',
    rbac_level: 'RBAC Nivel 1',
    description: 'Acceso total institucional a todos los eventos, reportes consolidados y listados de asistencia.',
    doc_type: 'CC',
    doc_number: '52489632',
    password: '52489632'
  },
  {
    id: 'staff-admin',
    name: 'Julián Montoya',
    email: 'julian.montoya@bienestar.edu.co',
    role: 'apoyo_administrativo',
    role_display: 'Apoyo Administrativo',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    gender: 'male',
    category_scope: 'all',
    rbac_level: 'RBAC Nivel 1',
    description: 'Acceso total a la información de eventos, soporte en mesas de registro y listados de asistencia.',
    doc_type: 'CC',
    doc_number: '79845120',
    password: '79845120'
  },
  {
    id: 'staff-deportes',
    name: 'Prof. Marcos Valenzuela',
    email: 'marcos.valenzuela@bienestar.edu.co',
    role: 'gestor_deportivo',
    role_display: 'Coordinador de Deportes y Recreación',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    gender: 'male',
    category_scope: 'deportes',
    rbac_level: 'RBAC Nivel 2',
    description: 'Acceso exclusivo a los eventos y listados de asistencia creados por este rol deportivo.',
    doc_type: 'CC',
    doc_number: '80123456',
    password: '80123456'
  },
  {
    id: 'staff-musica',
    name: 'Mtro. Camilo Restrepo',
    email: 'camilo.restrepo@bienestar.edu.co',
    role: 'gestor_cultural_musica',
    role_display: 'Gestor Cultural - Música',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    gender: 'male',
    category_scope: 'musica',
    rbac_level: 'RBAC Nivel 2',
    description: 'Acceso exclusivo a los eventos y listados de asistencia creados para música y ensambles.',
    doc_type: 'CC',
    doc_number: '1017234567',
    password: '1017234567'
  },
  {
    id: 'staff-danzas',
    name: 'Lic. Sandra Morales',
    email: 'sandra.morales@bienestar.edu.co',
    role: 'gestor_cultural_danzas',
    role_display: 'Gestor Cultural - Danzas',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    gender: 'female',
    category_scope: 'danzas',
    rbac_level: 'RBAC Nivel 2',
    description: 'Acceso exclusivo a los eventos y listados de asistencia de danzas creados por este rol.',
    doc_type: 'CC',
    doc_number: '43987654',
    password: '43987654'
  },
  {
    id: 'staff-psico',
    name: 'Psic. Valentina Quintero',
    email: 'valentina.quintero@bienestar.edu.co',
    role: 'psicologo',
    role_display: 'Orientación & Salud Mental',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    gender: 'female',
    category_scope: 'psicologia',
    rbac_level: 'RBAC Nivel 2',
    description: 'Acceso exclusivo a los talleres y listados de asistencia creados en psicología.',
    doc_type: 'CC',
    doc_number: '1020345678',
    password: '1020345678'
  },
  {
    id: 'staff-salud',
    name: 'Enf. Patricia Londoño',
    email: 'patricia.londono@bienestar.edu.co',
    role: 'enfermera',
    role_display: 'Atención Médica y Primeros Auxilios',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=200',
    gender: 'female',
    category_scope: 'salud',
    rbac_level: 'RBAC Nivel 2',
    description: 'Acceso exclusivo a las jornadas de salud y listados de asistencia creados en enfermería.',
    doc_type: 'CC',
    doc_number: '32567890',
    password: '32567890'
  }
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'ev-2026-01',
    code: 'EV-2026-01',
    title: 'Torneo Relámpago de Voleibol Mixto',
    description: 'Torneo interfacultades de integración rápida y salud cardiovascular.',
    category: 'deportes',
    date: '2026-10-28',
    time: '09:00 AM',
    location: 'Coliseo Principal',
    capacity: 60,
    registered_count: 48,
    attended_count: 38,
    status: 'active',
    cover_image: '/src/assets/images/event_volleyball_court_1790266140041.jpg',
    qr_enabled: true,
    created_by: 'staff-deportes',
    created_at: '2026-09-20T08:00:00Z'
  },
  {
    id: 'ev-2026-02',
    code: 'EV-2026-02',
    title: 'Festival de la Canción y Danzas',
    description: 'Muestra folclórica interuniversitaria y concurso de solistas.',
    category: 'musica',
    date: '2026-10-30',
    time: '02:00 PM',
    location: 'Auditorio Mayor',
    capacity: 200,
    registered_count: 180,
    attended_count: 145,
    status: 'active',
    cover_image: '/src/assets/images/event_folkloric_music_1790266151429.jpg',
    qr_enabled: true,
    created_by: 'staff-musica',
    created_at: '2026-09-21T09:30:00Z'
  },
  {
    id: 'ev-2026-03',
    code: 'EV-2026-03',
    title: 'Jornada de Vacunación y Salud Visual',
    description: 'Tamizaje optométrico gratuito y esquema complementario de inmunización.',
    category: 'salud',
    date: '2026-11-02',
    time: '08:00 AM',
    location: 'Bloque C - Enfermería',
    capacity: 150,
    registered_count: 110,
    attended_count: 89,
    status: 'active',
    cover_image: '/src/assets/images/event_health_screening_1790266161602.jpg',
    qr_enabled: true,
    created_by: 'staff-salud',
    created_at: '2026-09-22T10:15:00Z'
  },
  {
    id: 'ev-2026-04',
    code: 'EV-2026-04',
    title: 'Taller de Habilidades Emocionales',
    description: 'Manejo de estrés académico, resiliencia y técnicas de atención plena.',
    category: 'psicologia',
    date: '2026-11-04',
    time: '10:30 AM',
    location: 'Sala Conferencias 2',
    capacity: 30,
    registered_count: 28,
    attended_count: 22,
    status: 'active',
    cover_image: '/src/assets/images/event_mindfulness_workshop_1790266176598.jpg',
    qr_enabled: true,
    created_by: 'staff-psico',
    created_at: '2026-09-23T11:00:00Z'
  },
  {
    id: 'ev-2026-05',
    code: 'EV-2026-05',
    title: 'Encuentro Universitario de Danzas Tradicionales',
    description: 'Taller práctico de ritmos del caribe y presentación de comparsas universitarias.',
    category: 'danzas',
    date: '2026-11-08',
    time: '03:00 PM',
    location: 'Plazoleta Central',
    capacity: 80,
    registered_count: 65,
    attended_count: 52,
    status: 'active',
    cover_image: '/src/assets/images/event_folkloric_music_1790266151429.jpg',
    qr_enabled: true,
    created_by: 'staff-danzas',
    created_at: '2026-09-23T14:00:00Z'
  }
];

export const INITIAL_ATTENDEES: AttendanceRecord[] = [
  {
    id: 'att-1',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-1',
    name: 'Carlos Andrés Mendoza',
    email: 'cmendoza@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1024567890',
    ficha: 'Ficha 2825412 - ADSO',
    time: '09:48 AM',
    checked_in: true,
    pin: '1234',
    method: 'kiosk_pin',
    created_at: '2026-09-24T09:48:00Z'
  },
  {
    id: 'att-2',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-2',
    name: 'Laura Valentina Rojas',
    email: 'lrojas@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'TI',
    doc_number: '1019887766',
    ficha: 'Ficha 2825412 - ADSO',
    time: '09:51 AM',
    checked_in: true,
    pin: '4321',
    method: 'qr_scanner',
    created_at: '2026-09-24T09:51:00Z'
  },
  {
    id: 'att-3',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-3',
    name: 'Prof. Jorge Luis Pardo',
    email: 'jpardo@sena.edu.co',
    role: 'Instructor',
    doc_type: 'CC',
    doc_number: '79456123',
    ficha: 'Área de Deportes',
    time: '09:30 AM',
    checked_in: true,
    pin: '1122',
    method: 'kiosk_pin',
    created_at: '2026-09-24T09:30:00Z'
  },
  {
    id: 'att-4',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-4',
    name: 'Mariana Sofía Gómez',
    email: 'mgomez@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1033445566',
    ficha: 'Ficha 2711090 - Gestión',
    time: '--',
    checked_in: false,
    pin: '9988',
    created_at: '2026-09-24T08:00:00Z'
  },
  {
    id: 'att-5',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-5',
    name: 'David Eduardo Sánchez',
    email: 'dsanchez@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1022998877',
    ficha: 'Ficha 2825412 - ADSO',
    time: '09:54 AM',
    checked_in: true,
    pin: '7766',
    method: 'kiosk_pin',
    created_at: '2026-09-24T09:54:00Z'
  },
  {
    id: 'att-6',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-6',
    name: 'Dra. Natalia Osorio',
    email: 'nosorio@sena.edu.co',
    role: 'Funcionario',
    doc_type: 'CC',
    doc_number: '52889944',
    ficha: 'Bienestar / Fisioterapia',
    time: '09:40 AM',
    checked_in: true,
    pin: '5544',
    method: 'kiosk_pin',
    created_at: '2026-09-24T09:40:00Z'
  },
  {
    id: 'att-7',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-7',
    name: 'Felipe Antonio Castro',
    email: 'fcastro@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'TI',
    doc_number: '1098765432',
    ficha: 'Ficha 2798124 - Ciberseguridad',
    time: '--',
    checked_in: false,
    pin: '3322',
    created_at: '2026-09-24T08:10:00Z'
  },
  {
    id: 'att-8',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-8',
    name: 'Andrea Carolina Beltrán',
    email: 'abeltran@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1015667788',
    ficha: 'Ficha 2825412 - ADSO',
    time: '09:56 AM',
    checked_in: true,
    pin: '6655',
    method: 'qr_scanner',
    created_at: '2026-09-24T09:56:00Z'
  },
  {
    id: 'att-9',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-9',
    name: 'Héctor Fabio Ramírez',
    email: 'hramirez@sena.edu.co',
    role: 'Instructor',
    doc_type: 'CC',
    doc_number: '14889977',
    ficha: 'Coordinación Académica',
    time: '--',
    checked_in: false,
    pin: '2211',
    created_at: '2026-09-24T08:15:00Z'
  },
  {
    id: 'att-10',
    event_id: 'ev-2026-01',
    event_title: 'Torneo Relámpago de Voleibol Mixto',
    participant_id: 'p-10',
    name: 'Sara Lucía Martínez',
    email: 'smartinez@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1044778899',
    ficha: 'Ficha 2825412 - ADSO',
    time: '09:58 AM',
    checked_in: true,
    pin: '8899',
    method: 'kiosk_pin',
    created_at: '2026-09-24T09:58:00Z'
  },
  // Attendees for ev-2026-02 (Festival de la Canción y Danzas - Gestor Cultural Música)
  {
    id: 'att-mus-1',
    event_id: 'ev-2026-02',
    event_title: 'Festival de la Canción y Danzas',
    participant_id: 'p-mus-1',
    name: 'Mateo Alejandro Ríos',
    email: 'marios@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1077334455',
    ficha: 'Ficha 2831200 - Multimedia',
    time: '02:15 PM',
    checked_in: true,
    pin: '2345',
    method: 'qr_scanner',
    created_at: '2026-09-24T14:15:00Z'
  },
  {
    id: 'att-mus-2',
    event_id: 'ev-2026-02',
    event_title: 'Festival de la Canción y Danzas',
    participant_id: 'p-mus-2',
    name: 'Valeria Cárdenas Mora',
    email: 'vcardenas@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'TI',
    doc_number: '1088443322',
    ficha: 'Ficha 2754321 - Animación 3D',
    time: '02:22 PM',
    checked_in: true,
    pin: '5432',
    method: 'kiosk_pin',
    created_at: '2026-09-24T14:22:00Z'
  },
  {
    id: 'att-mus-3',
    event_id: 'ev-2026-02',
    event_title: 'Festival de la Canción y Danzas',
    participant_id: 'p-mus-3',
    name: 'Lic. Andrés Felipe Suárez',
    email: 'asuarez@sena.edu.co',
    role: 'Instructor',
    doc_type: 'CC',
    doc_number: '71987654',
    ficha: 'Música y Expresión',
    time: '--',
    checked_in: false,
    pin: '3456',
    created_at: '2026-09-24T13:00:00Z'
  },
  // Attendees for ev-2026-03 (Jornada de Vacunación - Enfermería)
  {
    id: 'att-sal-1',
    event_id: 'ev-2026-03',
    event_title: 'Jornada de Vacunación y Salud Visual',
    participant_id: 'p-sal-1',
    name: 'Claudia Marcela Peña',
    email: 'cpena@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1012345678',
    ficha: 'Ficha 2899001 - Enfermería',
    time: '08:12 AM',
    checked_in: true,
    pin: '9876',
    method: 'kiosk_pin',
    created_at: '2026-09-24T08:12:00Z'
  },
  {
    id: 'att-sal-2',
    event_id: 'ev-2026-03',
    event_title: 'Jornada de Vacunación y Salud Visual',
    participant_id: 'p-sal-2',
    name: 'Dr. Roberto Estupiñán',
    email: 'restupinan@sena.edu.co',
    role: 'Funcionario',
    doc_type: 'CC',
    doc_number: '19876543',
    ficha: 'Administración Sede',
    time: '08:30 AM',
    checked_in: true,
    pin: '6789',
    method: 'manual_staff',
    created_at: '2026-09-24T08:30:00Z'
  },
  {
    id: 'att-sal-3',
    event_id: 'ev-2026-03',
    event_title: 'Jornada de Vacunación y Salud Visual',
    participant_id: 'p-sal-3',
    name: 'Juliana Paz Henao',
    email: 'jpaz@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'TI',
    doc_number: '1099887766',
    ficha: 'Ficha 2844556 - Contabilidad',
    time: '--',
    checked_in: false,
    pin: '4567',
    created_at: '2026-09-24T07:45:00Z'
  },
  // Attendees for ev-2026-04 (Taller Habilidades Emocionales - Psicología)
  {
    id: 'att-psi-1',
    event_id: 'ev-2026-04',
    event_title: 'Taller de Habilidades Emocionales',
    participant_id: 'p-psi-1',
    name: 'Sebastián Caicedo López',
    email: 'scaicedo@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1034567891',
    ficha: 'Ficha 2825412 - ADSO',
    time: '10:35 AM',
    checked_in: true,
    pin: '8765',
    method: 'kiosk_pin',
    created_at: '2026-09-24T10:35:00Z'
  },
  {
    id: 'att-psi-2',
    event_id: 'ev-2026-04',
    event_title: 'Taller de Habilidades Emocionales',
    participant_id: 'p-psi-2',
    name: 'Daniela Vivas Ortiz',
    email: 'dvivas@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'TI',
    doc_number: '1022334411',
    ficha: 'Ficha 2711090 - Gestión',
    time: '--',
    checked_in: false,
    pin: '3210',
    created_at: '2026-09-24T09:30:00Z'
  },
  // Attendees for ev-2026-05 (Danzas Tradicionales - Gestor Cultural Danzas)
  {
    id: 'att-dan-1',
    event_id: 'ev-2026-05',
    event_title: 'Encuentro Universitario de Danzas Tradicionales',
    participant_id: 'p-dan-1',
    name: 'Camila Andrea Buitrago',
    email: 'cbuitrago@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1018998877',
    ficha: 'Ficha 2831200 - Multimedia',
    time: '03:10 PM',
    checked_in: true,
    pin: '7654',
    method: 'qr_scanner',
    created_at: '2026-09-24T15:10:00Z'
  },
  {
    id: 'att-dan-2',
    event_id: 'ev-2026-05',
    event_title: 'Encuentro Universitario de Danzas Tradicionales',
    participant_id: 'p-dan-2',
    name: 'Santiago Morales Perea',
    email: 'smorales@sena.edu.co',
    role: 'Aprendiz',
    doc_type: 'CC',
    doc_number: '1029887766',
    ficha: 'Ficha 2825412 - ADSO',
    time: '03:15 PM',
    checked_in: true,
    pin: '6543',
    method: 'kiosk_pin',
    created_at: '2026-09-24T15:15:00Z'
  }
];
